apiVersion: v1
kind: Secret
metadata:
  name: {{ include "port-self-hosted-github-app.secretName" . }}
  labels:
    {{- include "port-self-hosted-github-app.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: opaque
data:
  PORT_CLIENT_ID: {{ required "Port Client ID is required" .Values.secret.secrets.portClientId | b64enc }}
  PORT_CLIENT_SECRET: {{ required "Port Client Secret is required" .Values.secret.secrets.portClientSecret | b64enc }}
  WEBHOOK_SECRET: {{ required "Wehbook Secret is required" .Values.secret.secrets.webhookSecret | b64enc }}
  PRIVATE_KEY: {{ required "Private key is required" .Values.secret.secrets.privateKey | b64enc }}