nameOverride: ""
fullnameOverride: ""

port:
  clientId: ""
  clientSecret: ""
  baseUrl: https://api.getport.io

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

imagePullPolicy: Always

initializePortResources: true

scheduledResyncInterval: 60

service:
  enabled: true
  type: ClusterIP
  port: 8000
  
ingress:
  enabled: false
  annotations: {}
  host: null
  
integration:
  identifier: ""
  version: ""
  type: ""
  config: {}
  secrets: {}
  eventListener:
    type: "KAFKA"
    brokers: "b-1-public.publicclusterprod.t9rw6w.c1.kafka.eu-west-1.amazonaws.com:9196,b-2-public.publicclusterprod.t9rw6w.c1.kafka.eu-west-1.amazonaws.com:9196,b-3-public.publicclusterprod.t9rw6w.c1.kafka.eu-west-1.amazonaws.com:9196"