apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "port-ocean.configMapName" . }}
data:
  config.yaml: |-
    port:
      clientId: "{{ printf "{{ from env PORT_CLIENT_ID }}" }}"
      clientSecret: "{{ printf "{{ from env PORT_CLIENT_SECRET }}" }}"
      baseUrl: {{ .Values.port.baseUrl | quote }}
    initializePortResources: {{ .Values.initializePortResources | default false }}
    scheduledResyncInterval: {{ .Values.scheduledResyncInterval }}
    eventListener: 
      {{- range $key, $value := .Values.integration.eventListener }}
      {{ $key }}: {{ $value | quote }}
      {{- end}}
    integration:
      identifier: {{ .Values.integration.identifier }}
      type: {{ .Values.integration.type }}
      config:
        {{- if .Values.integration.config -}}
        {{- range $key, $value := .Values.integration.config }}
        {{ $key }}: {{ $value | quote }}
        {{- end -}}
        {{- end -}}
        {{- if .Values.integration.secrets -}}
        {{- range $key, $value := .Values.integration.secrets }}
        {{ $key }}: "{{ printf "{{ from env %s }}" $key }}"
        {{- end -}}
        {{- end -}}