apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "port-ocean.configMapName" . }}
data:
  OCEAN__PORT__BASE_URL: {{ .Values.port.baseUrl | quote }}
  OCEAN__INITIALIZE_PORT_RESOURCES: "{{ .Values.initializePortResources | default false }}"
  {{- if .Values.scheduledResyncInterval }}
  OCEAN__SCHEDULED_RESYNC_INTERVAL: "{{ .Values.scheduledResyncInterval }}"
  {{- end }}
  {{- if .Values.clientTimeout }}
    OCEAN__CLIENT_TIMEOUT: "{{ .Values.clientTimeout }}"
  {{- end }}
  OCEAN__EVENT_LISTENER: {{ .Values.integration.eventListener | toJson | quote }}
  {{- if .Values.integration.identifier }}
  OCEAN__INTEGRATION__IDENTIFIER: "{{ .Values.integration.identifier }}"
  {{- end }}
  {{- if .Values.integration.type }}
  OCEAN__INTEGRATION__TYPE: "{{ .Values.integration.type }}"
  {{- end }}
  {{- if .Values.integration.config }}
  {{- range $key, $value := .Values.integration.config }}
  OCEAN__INTEGRATION__CONFIG__{{ $key | snakecase | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
