{{- if .Values.service  }}
{{- if (eq .Values.service.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "port-ocean.serviceName" . }}
  labels:
    {{- include "port-ocean.labels" $ | nindent 4 }}
  annotations:
    {{- if .Values.service.annotations }}
      {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ocean-port
      protocol: TCP
      port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "port-ocean.deploymentName" . }}
{{- end }}
{{- end }}
